Bootstrap
HappyCodeHere/events-spa-server pull request #11
Opened 2018-12-22 18:29 UTC by Chechko-Ivan

2018-12-22 23:28 UTC, happylolonly requested changes
@Chechko-Ivan , есть замечания.
Задача сделана, но код не ок.

Стили не так важны как js, но чем больше проект, тем сложнее их поддерживать. Растут они очень быстро. У тебя много дублирований и каких то левых свойств.
Стили которые относятся только к компоненту должны быть рядом с ним.
Общие стили можно вынести в index.scss

Так же что то стало со шрифтом, очень заметно.

Необходимо это исправить для мержа.

2018-12-22 23:28 UTC, happylolonly commented on client/public/index.html
> +    <!-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crosso
@Chechko-Ivan , задачу нужно доделывать до конца, т.е удалить это тоже.

2018-12-22 23:28 UTC, happylolonly commented on client/src/components/EventItem/EventItem.js
> +import moment, { now } from 'moment';
Что это за now?
Поставь sourcetree и проверяй что коммитишь

2018-12-22 23:28 UTC, happylolonly commented on client/src/components/EventItem/EventItem.js
> +
:thumbsup:

2018-12-22 23:28 UTC, happylolonly commented on client/src/components/EventItem/EventItem.scss
> +      color: #337ab7;
Можем такие цвета выносить в scss переменные? link-color

2018-12-22 23:28 UTC, happylolonly commented on client/src/components/EventItem/EventItem.scss
> +        text-decoration: underline;
стили можно поднять выше и написать 1 раз а не 2.

так же нужно перенести .tag__container в cкоуп .event-item - название компонента, такие же стили

2018-12-22 23:28 UTC, happylolonly commented on client/src/components/Header/Header.scss
> +  .santa::after {
Header сделан круто, но стили для санты нужно перенести в его компонент.

2018-12-22 23:28 UTC, happylolonly commented on client/src/components/Header/Header.scss
> +    @media screen and (max-width: 992px) {
media screen нужен разве?

2018-12-22 23:28 UTC, happylolonly commented on client/src/components/common/Textarea/Textarea.scss
> +        background-image: none;
для чего background-image и line-height?

2018-12-22 23:28 UTC, happylolonly commented on client/src/index.scss
> +    line-height: 1.42857143;
и тут line-height

2018-12-22 23:28 UTC, happylolonly commented on client/src/index.scss
> +.checkbox, .radio {
Для чего класс .radio?
Перенеси стили в компонент чекбокса.

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/AboutPage/AboutPage.scss
> +      color: #23527c;
Давай общие стили для ссылок в одном месте напишем. В index.sccs

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/AboutPage/FeedbackForm/FeedbackForm.scss
> +      cursor: pointer;
А так разве там не pointer?

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/EventPage/EventDetail.scss
> +      transition: color 0.3s ease;
Тоже в одно место.
В компонентах ок переопределять что-нибудь, но не писать все заново.

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/EventPage/EventDetailFooter/EventDetailFooter.scss
> +        padding-left: 0;
Было бы круто попробовать сделать a, .btn-link {}, чтобы все было в одном месте

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/TodayPage/Filters/Filters.scss
> +    cursor: pointer;
На button нету cursor: pointer ? О_о...

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/TodayPage/Filters/Filters.scss
> +.today-page-container > .filters > button {
Фильтры и так в скоупе today-page-container, нужно убрать

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/TodayPage/Search/Search.scss
> +.form-control {
Что-то мне эти стили тут очень не нравятся, давай тут используем компонент `components/Input`, и стили перенесем туда, а тут оставим очень мало, если будут нужны

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/TodayPage/TodayPage.js
> +        return <h3 className="today-page__title">Мероприятия на {`${+day} ${monthRU[+month - 1].toLowerCase()}`}</h3>
Для чего классы?

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/TodayPage/TodayPageContainer.scss
> +.btn-toggle-calendar {
Нужно удалить

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/TodayPage/TodayPageContainer.scss
> +    &:focus {
стили в вынести

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/TodayPage/TodayPageContainer.js
> +          {this.state.currentFilter === 'certain' && <button className="btn-toggle-calendar" onClick={this.toggleCalendar}>{!this.state.isShowCalendar ? 'Показать' : 'Cкрыть'} календарь</button>}
Зачем тут новый класс?

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/TodayPage/TodayPageContainer.js
> +              <button className="show-more" onClick={this.loadMore}>Показать еще</button>}
Нужно вернуть .btn-link

2018-12-22 23:28 UTC, happylolonly commented on client/src/pages/WeekEvents/Search/Search.scss
> +.btn-success {
Вообще не понял почему тут эти стили.

2018-12-25 12:44 UTC, Chechko-Ivan commented on client/src/components/Header/Header.scss
> +    @media screen and (max-width: 992px) {
https://sass-lang.com/documentation/file.SASS_REFERENCE.html#media

2018-12-25 12:47 UTC, Chechko-Ivan commented on client/src/components/common/Textarea/Textarea.scss
> +        background-image: none;
line-height для чего нужен? Можешь почитать что он делает)

2018-12-26 09:03 UTC, Chechko-Ivan commented on client/src/pages/AboutPage/FeedbackForm/FeedbackForm.scss
> +      cursor: pointer;
no

2018-12-26 10:41 UTC, happylolonly approved these changes
@Chechko-Ivan , выглядит ок теперь)

Ответь на коммент + нужно исправить там конфликт с `Header`.
И что по шрифту там получилось?

После этого смержим уже)

2018-12-26 10:41 UTC, happylolonly commented on client/src/components/Header/Header.scss
> +        color: #fff;
Для чего тут цвет если он выше указан?

2018-12-26 10:41 UTC, happylolonly commented on client/src/index.scss
> +a, .btn--link {
Ура)

2018-12-26 10:48 UTC, Chechko-Ivan commented on client/src/components/Header/Header.scss
> +        color: #fff;
Если явно не указать то будут срабатывать стили на эти состояния для обычных ссылку, стили которых определенны в index.scss

2018-12-26 11:47 UTC, merged

2018-12-26 11:48 UTC, happylolonly commented
task #5