Added button scroll up on TodayPage
HappyCodeHere/events-spa-server pull request #12
Opened 2018-12-23 09:07 UTC by Chechko-Ivan

2018-12-23 09:46 UTC, happylolonly requested changes

2018-12-23 09:46 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.scss
> +  outline: none;
Насколько outline мешает? Макеев бы сказал что это не ок.

2018-12-23 09:46 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.scss
> +  cursor: pointer;
cursor: pointer зачем?

2018-12-23 09:46 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.scss
> +@import '../../constants/style/colors';
Для чего импорт тут?

2018-12-23 09:46 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.js
> +    if (window.pageYOffset > 300) {
Напиши тернарником плз, будет меньше требовать читать кода

2018-12-23 09:46 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.js
> +    window.scroll(0, window.pageYOffset - this.props.scrollStep);
Проверь плз что мы в минус не можем уйти.
И интервал будет висеть в памяти.

2018-12-23 09:46 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.js
> +  scrollStep: PropTypes.number.isRequired,
Давай лучше пропсы в константы в самом компоненте вынесем. Сейчас я думаю такая гибкость не нужна для этой кнопки.

2018-12-23 09:46 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.js
> +    let interval = setInterval(this.scrollStep.bind(this), this.props.delay);
interval давай в this, без стейта

.bind тут нельзя делать, будет создаваться новая функция каждый раз

2018-12-23 09:46 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.js
> +            <button className="scroll-up-button" onClick={() => { this.scrollToTop() }}>
Давай тут через обычный if, будет выглядеть проще.

2018-12-23 09:48 UTC, Chechko-Ivan commented on client/src/components/ScrollUpButton/ScrollUpButton.scss
> +  outline: none;
Верстка и так показывает что на нем фокус, делая его более ярким.. поэтому outline можно убрать

2018-12-23 09:51 UTC, Chechko-Ivan commented on client/src/components/ScrollUpButton/ScrollUpButton.scss
> +  cursor: pointer;
Потому что мне нравиться видеть на интерактивных элементах cursor: pointer
Вот еще Issues по этому поводу в [normalize.css](https://github.com/necolas/normalize.css/issues/371)

2018-12-23 19:16 UTC, happylolonly requested changes

2018-12-23 19:16 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.js
>  const propTypes = {
propTypes пока не нужны, нужно удалить

2018-12-23 19:16 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.js
> +    window.pageYOffset > 300 ? this.setState({ showButton: true }) : this.setState({ showButton: false })
Сильно понятнее стало?)

this.setState({ showButton: window.pageYOffset > 300 })

2018-12-23 19:16 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.js
> +    window.scroll(0, window.pageYOffset - 50);
Я просил в константы значения вынести, но лад)

2018-12-23 19:16 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.js
> +          Вверх
Не нужная внешняя функция

2018-12-23 19:16 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.js
> +    return null;
Лучше null в if, а нормальный код на отступ влево.
Будет код сложнее, тяжелее читать.

2018-12-23 19:16 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.scss
> -@import '../../constants/style/colors';
Ничего не сломалось?)

2018-12-23 19:19 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.js
> +    let interval = setInterval(this.scrollStep, 15);
Компонент должен обновляться при изменении интервала?
Если нет, в стейт его ложить не нужно

2018-12-23 19:23 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.scss
> +  cursor: pointer;
Забыл что кнопки без него идут по дефолту.
Это важное свойство для кнопки, добавь его плз в index.scss

2018-12-23 19:30 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.scss
> +  outline: none;
А почему он убирается не в псевдоклассе тогда, а в основных стилях?

2018-12-25 10:34 UTC, happylolonly commented on client/src/components/ScrollUpButton/ScrollUpButton.js
> +    // this.setState({ interval: interval });
С this правильно, удали коммент плз

2018-12-25 12:28 UTC, chechkovania commented on client/src/components/ScrollUpButton/ScrollUpButton.js
> +    window.pageYOffset > 300 ? this.setState({ showButton: true }) : this.setState({ showButton: false })
Вроде бы и так и так было легко прочитать)

2018-12-25 13:39 UTC, merged

2018-12-25 21:03 UTC, happylolonly reviewed
Теперь все ок)

2018-12-25 21:04 UTC, happylolonly reviewed
Ок)

2018-12-25 21:25 UTC, happylolonly commented
fixes #4