Fixed undefined action type
HappyCodeHere/events-spa-server pull request #18
Opened 2019-01-03 22:40 UTC by vvitto

Ошибка появлялась из-за старого redux-logger в случаях, когда в экшене использовался await (https://github.com/LogRocket/redux-logger/issues/290). В redux-devtools такого нет. Так же я немного порефакторил events actions.

2019-01-04 10:39 UTC, happylolonly commented on package.json
> +		"react-router": "^4.3.1",
А для чего react-router?

2019-01-04 10:45 UTC, vvitto commented
@happylolonly у вас в файле routes он импортится, а в package.json'e его нет

2019-01-04 11:49 UTC, happylolonly requested changes
@vvitto , поставь плз плагин для prettier и верни ненужное форматирование назад.

И посмотри комментарии.

2019-01-04 11:49 UTC, happylolonly commented on client/src/actions/events.js
> +export const eventLoadedWithSuccess = createAction(types.LOAD_EVENT_SUCCESS, (data) => data);
Я где-то в нете смотрел что вроде payload прокидывается автоматически, эта функция нужна тут?

2019-01-04 11:49 UTC, happylolonly commented on client/src/actions/events.js
> -      return events[key];
Какой то копипаст код, но там логика что нужно отправить значения которые true.
Сейчас как понимаю это будет сломано.

2019-01-04 11:49 UTC, happylolonly commented on client/src/actions/events.js
> +    return axios.get(`${API}/events`, {
А чего оно в промис превратилось?)

2019-01-04 11:49 UTC, happylolonly commented on client/src/actions/events.js
> -      dispatch({ type: types.SETUP_EVENTS_LIST, payload: event.data.model }); // возможно костыль, потом посмотреть
Верни плз этот коммент, может пригодится потом.

2019-01-04 11:50 UTC, happylolonly commented on package.json
> +		"react-router": "^4.3.1",
Странно что в routes так написано...
Вроде react-router не нужен когда есть react-router-dom

2019-01-04 16:31 UTC, vvitto commented on client/src/actions/events.js
> +    return axios.get(`${API}/events`, {
Ну мне показалось, что с промисом код выглядит аккуратнее, чем с try catch. Вроде бы как код не ломается. Но поправь меня если я ошибаюсь)

2019-01-04 17:14 UTC, happylolonly commented on client/src/actions/events.js
> +    return axios.get(`${API}/events`, {
Аккуратнее/не аккуратнее - дело привычки. Я когда-то не понимал как можно несколько стрелочных функций в 1 строку писать.

Большинство рекомендуют async/await вместо промисов, не просто так же их сделали)
Верни назад плз,
+ посмотри что после prettier'a назад, максимально минимально кода изменено относительно основной ветки

2019-01-04 17:16 UTC, happylolonly commented on client/src/actions/events.js
> +export const eventLoadedWithSuccess = createAction(types.LOAD_EVENT_SUCCESS);
Проверил что так работает?) Потому что я не уверен полностью)

2019-01-04 17:17 UTC, happylolonly commented on client/src/actions/events.js
> +    const activeSources = Object.keys(sources)
👍

2019-01-04 17:17 UTC, happylolonly commented on client/src/routes.js
> +import { Redirect } from 'react-router-dom';
Крутяк

2019-01-04 17:58 UTC, vvitto commented on client/src/actions/events.js
> +export const eventLoadedWithSuccess = createAction(types.LOAD_EVENT_SUCCESS);
работает)

2019-01-05 21:13 UTC, happylolonly approved these changes

2019-01-05 21:19 UTC, merged

2019-01-05 21:19 UTC, happylolonly commented
@vvitto , nice!