changes after deploy prod-setting page
HappyCodeHere/events-spa-server pull request #31
Opened 2019-01-17 20:25 UTC by raven41k

2019-01-17 20:54 UTC, happylolonly requested changes

2019-01-17 20:54 UTC, happylolonly commented on client/src/pages/SettingsPage/Sources/Sources.js
> +                <a target="_blank" href={`//${text}`}>{text}</a>
Rename 'text' to 'link' please.

2019-01-17 20:54 UTC, happylolonly commented on client/src/pages/SettingsPage/Sources/Sources.js
> +                <a target="_blank" href={`//${text}`}>{text}</a>
Why '//' better than 'www.' ?

2019-01-17 21:28 UTC, raven41k commented on client/src/pages/SettingsPage/Sources/Sources.js
> +                <a target="_blank" href={`//${text}`}>{text}</a>
'//' works correctly

2019-01-25 03:50 UTC, happylolonly commented
fix #25

2019-01-26 15:55 UTC, happylolonly approved these changes

2019-01-26 15:56 UTC, merged